apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-calculator
  labels:
    app: web-calculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-calculator
  template:
    metadata:
      labels:
        app: web-calculator
    spec:
      containers:
        - name: web-calculator
          image: web-calculator:latest  # Make sure this tag exists locally.
          imagePullPolicy: Never  # Ensures the local image is used.
          ports:
            - containerPort: 3000
