apiVersion: v1
kind: Service
metadata:
  name: web-calculator
spec:
  type: NodePort  # Change to NodePort for external access
  selector:
    app: web-calculator
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
