version: '3.8'

services:
  calculator:
    container_name: calculator-service
    image: web-calculator:latest
    ports:
      - "3000:3000"
    hostname: calculator
    restart: unless-stopped
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first  # Zero downtime update
