version: "3.8"
services:
  web-calculator:
    container_name: web-calculator
    image: web-calculator:latest

    env_file:
      - ${WEB-CALCULATER_ENV}
      
    ports:
      - "1110:3000"
    restart: always


