version: "10.1"
services:
  web-calculator:
    container_name: web-calculator
    image: web-calculator:latest

    env_file:
      - ${WEB_CALCULATOR_ENV}
      
    ports:
      - "1110:3000"
    restart: always


