# version: '3.8'

# services:
#   calculator:
#     container_name: calculator-service
#     image: web-calculator:latest
#     ports:
#       - "3000:3000"
#     hostname: calculator
#     restart: unless-stopped
#     deploy:
#       replicas: 1
#       update_config:
#         parallelism: 1
#         order: start-first  # Zero downtime update

version: '3.8'

services:
  calculator-blue:
    container_name: calculator-blue
    image: web-calculator:latest  # Updated dynamically by Jenkins
    ports:
      - "3001:3000"   # Temporary port to avoid conflicts
    hostname: calculator-blue
    restart: unless-stopped
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first  # Ensures zero downtime

  calculator-green:
    container_name: calculator-green
    image: web-calculator:previous  # The stable version
    ports:
      - "3000:3000"   # Main traffic always points here
    hostname: calculator-green
    restart: unless-stopped
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first  # Ensures zero downtime

